name: Test build DEB package
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - "clearbot"

jobs:
  build-debian:
    runs-on: ARM64
    container: ros:foxy
    steps:
      - uses: actions/checkout@v3
      - name: Setup apt repo
        env:
          APTSERVER_USER: ${{ secrets.APTSERVER_USER }}
          APTSERVER_PASSWORD: ${{ secrets.APTSERVER_PASSWORD }}
        run: |
          sudo apt update
          sudo apt install -y wget software-properties-common
          wget -qO - https://aptserver.clearbot.dev/pubkey | sudo apt-key add -
          echo "machine https://aptserver.clearbot.dev\nlogin $APTSERVER_USER\npassword $APTSERVER_PASSWORD" >> /etc/apt/auth.conf.d/clearbot.conf
          sudo add-apt-repository 'deb https://aptserver.clearbot.dev focal main'
        working-directory: ./cv_bridge
      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt install -y dh-make fakeroot opencv-libs opencv-main opencv-python opencv-dev libboost-all-dev
          wget https://repo.download.nvidia.com/jetson/common/pool/main/c/cudnn/libcudnn8_8.6.0.166-1+cuda11.4_arm64.deb
          wget https://repo.download.nvidia.com/jetson/common/pool/main/c/cudnn/libcudnn8-dev_8.6.0.166-1+cuda11.4_arm64.deb
          wget https://repo.download.nvidia.com/jetson/common/pool/main/c/cuda-toolkit-11-4/cuda-toolkit-11-4_11.4.19-1_arm64.deb
          sudo apt install ./cuda-toolkit-11-4_11.4.19-1_arm64.deb
          sudo dpkg -i libcudnn8_8.6.0.166-1+cuda11.4_arm64.deb libcudnn8-dev_8.6.0.166-1+cuda11.4_arm64.deb
          export PATH=/usr/local/cuda-11.4/bin${PATH:+:${PATH}}
        working-directory: ./cv_bridge
      - name: fakeroot
        run: fakeroot debian/rules binary
        working-directory: ./cv_bridge
      - name: Debian file
        id: deb-file-name
        run: |
          cd .. && echo DEB_FILE="$(pwd)/$(find . -name "ros-foxy-clearbot-cv-bridge*.deb" | sed -r 's/^.{2}//')" >> "$GITHUB_OUTPUT"
        working-directory: ./cv_bridge
      - name: Export deb file artifact
        uses: actions/upload-artifact@v3
        with:
          name: built deb file
          path: ${{ steps.deb-file-name.outputs.DEB_FILE }}
          if-no-files-found: error
